const json1 = {
    "artefacts":[
       {
          "type":"M",
          "x":0,
          "y":3
       },
       {
          "type":"M",
          "x":0,
          "y":5
       },
       {
          "type":"M",
          "x":1,
          "y":3
       },
       {
          "type":"M",
          "x":1,
          "y":5
       },
       {
          "type":"M",
          "x":2,
          "y":2
       },
       {
          "type":"M",
          "x":2,
          "y":5
       },
       {
          "type":"M",
          "x":3,
          "y":1
       },
       {
          "type":"M",
          "x":3,
          "y":6
       },
       {
          "type":"M",
          "x":4,
          "y":1
       },
       {
          "type":"M",
          "x":4,
          "y":5
       },
       {
          "type":"M",
          "x":5,
          "y":0
       },
       {
          "type":"M",
          "x":5,
          "y":2
       },
       {
          "type":"M",
          "x":5,
          "y":4
       },
       {
          "type":"M",
          "x":5,
          "y":5
       },
       {
          "type":"M",
          "x":5,
          "y":6
       },
       {
          "type":"M",
          "x":6,
          "y":0
       },
       {
          "type":"M",
          "x":6,
          "y":1
       },
       {
          "type":"M",
          "x":6,
          "y":2
       },
       {
          "type":"M",
          "x":6,
          "y":7
       },
       {
          "type":"M",
          "x":6,
          "y":8
       },
       {
        "type":"M",
        "x":7,
        "y":2
        },
       {
          "type":"M",
          "x":7,
          "y":4
       },
       {
          "type":"M",
          "x":7,
          "y":5
       },
       {
          "type":"M",
          "x":7,
          "y":6
       },
       {
          "type":"M",
          "x":7,
          "y":7
       },
       {
        "type":"M",
        "x":8,
        "y":2
     },
       {
          "type":"M",
          "x":8,
          "y":4
       },
       {
          "type":"M",
          "x":8,
          "y":5
       },
       {
          "type":"M",
          "x":8,
          "y":6
       },
       {
          "type":"M",
          "x":8,
          "y":7
       },
       {
        "type":"M",
        "x":9,
        "y":2
     },
       {
          "type":"M",
          "x":9,
          "y":4
       },
       {
          "type":"M",
          "x":9,
          "y":5
       },
       {
          "type":"M",
          "x":9,
          "y":6
       },
       {
          "type":"M",
          "x":9,
          "y":7
       },
       {
        "type":"M",
        "x":10,
        "y":3
     },
    ],
    "lumicycles":[
       {
          "joueur":1,
          "points":[
             {
                "x":6,
                "y":3
             }            
          ],
          "artefacts":[
 
          ]
       },
       {
          "joueur":2,
          "points":[
             {
                "x":18,
                "y":18
             }
          ],
          "artefacts":[
 
          ]
       }
    ],
    "config":{
       "id":60,
       "tour":1,
       "maxX":30,
       "maxY":20,
       "nbJoueurs":2,
       "nbVehicules":1
    }
 };
 /************************************* */

 module.exports = {json1};